### ISSUE TITLE
Impressão

### ISSUE THREAD

**Issue by andrevandal** [rafaelmotta/bematech-printer#2]
Como que realiza a impressão? Rodei o npm install, depois npm start e só apareceu a janela de debug.

**Comment by rafaelmotta** [comment]
Vou dar um update amanhã no projeto ensinando.

**Comment by oAllanWeb** [comment]
Como testar?

**Comment by rafaelmotta** [comment]
Estou gerando uma documentação agora mesmo... até hoje coloco no ar e se vcs tiverem alguma duvida, só falar

**Comment by rafaelmotta** [comment]
Galera, dei uma melhorada na documentação. Infelizmente não tive tanto tempo. Vejam se conseguem rodar.
