### ISSUE TITLE
Duvida - Impressão inline

### ISSUE THREAD

**Issue by jfollmann** [rafaelmotta/bematech-printer#9]
Gostaria de saber se você tem um exemplo de como realizar o alinhamento diferente para a mesma linha. 
Abaixo segue um exemplo que estou montando para imprimir uma "grade" de produtos.

Nome do Produto (alinhado à esquerda)
Qtd do Produto (alinhado ao centro)
Valor do Produto (alinhado à direita)

```xml
<root cut="full">
  <line align="center" textTransform="bold">Impressão de Teste</line>
  <line></line>

  <line textTransform="bold" align="center">Cliente: {{ clientName }}</line>
  <line align="center">--------------------------------------------------</line>
  <line></line>
  <line textTransform="bold" align="center">PRODUTOS</line>
  <line align="center">{{products.length}} produtos informados:</line>
  {{#products}}
  <line display="inline" align="left">#Name {{name}}</line>
  <line display="inline" align="center">#Qtd {{qtd}}</line>
  <line display="inline" align="right">#Value {{value}}</line>
  <line></line>
  {{/products}}
</root>

```

Porém, com essa configuração de alinhamento, a aplicação sempre imprime alinhado à esquerda. Você sabe me dizer como devo configurar a linha para imprimir corretamente?

Além disso, parabéns pelo trabalho e pela iniciativa de compartilhar :clap: :clap:

Obrigado pelo auxilio.

**Comment by jfollmann** [comment]
Já tentei desta maneira também: 

```xml
  {{#products}}
  <line align="left">#Name {{name}}</line>
  <line display="inline" align="left">#Qtd {{qtd}}</line>
  <line align="right">#Value {{value}}</line>
  {{/products}}
  <line></line>
```

**Comment by rafaelmotta** [comment]
@jfollmann infelizmente nao tenho mais acesso a uma impressora pra testar.

Se vc quer fazer algo de forma tabular (acho que é isso), terias que dar uma olhada no manual da bematech e adicionar esses metodos no arquivo commands.js.

**Comment by rafaelmotta** [comment]
@jfollmann nao tenho mais acesso a essa impressora, já que nao moro mais no br.

Por favor, tenta dar uma olhada no manual da bematech e adicionar novos comandos no arquivo commands.js
